### ISSUE TITLE
Fatal exception when USB unplug

### ISSUE THREAD

**Issue by imberest** [ksksue/FTDriver#15]
Hi ksksue,
Very nice work, its working nice, but i have a question. 
When i unplug the USB it throws Fatal exception

```
01-28 15:08:26.580: E/AndroidRuntime(6074): FATAL EXCEPTION: Thread-211
01-28 15:08:26.580: E/AndroidRuntime(6074): Process: lt.vp.rightpanelusb, PID: 6074
01-28 15:08:26.580: E/AndroidRuntime(6074): java.lang.NullPointerException
01-28 15:08:26.580: E/AndroidRuntime(6074):     at jp.ksksue.driver.serial.FTDriver.read(FTDriver.java:313)
01-28 15:08:26.580: E/AndroidRuntime(6074):     at jp.ksksue.driver.serial.FTDriver.read(FTDriver.java:257)
01-28 15:08:26.580: E/AndroidRuntime(6074):     at lt.vp.rightpanelusb.RightActivity$2.run(RightActivity.java:603)
01-28 15:08:26.580: E/AndroidRuntime(6074):     at java.lang.Thread.run(Thread.java:841)
```

603 line: 

```
bytesAvailable = mSerial.read(rbuf);
```

**Comment by imberest** [comment]
Just in case someone will have similar problem :) o it like this, works great!

```
if(mSerial.begin(SERIAL_BAUDRATE))
   len = mSerial.read(rbuf);
```
